openapi: 3.0.1
info:
  title: '@jupiterone/graph-checkmarx'
  description: A JupiterOne Integration for https://www.checkmarx.com/
  x-cortex-git:
    github:
      repository: JupiterOne/graph-checkmarx
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-checkmarx'
  x-cortex-service-groups:
    - tier-4
